config/routes.rb
Rails.application.routes.draw do
  get 'contact/index', to: 'contact#index', as: :contact
  get 'about/index', to: 'about#index', as: :about
  get 'gallery/index', to: 'gallery#index', as: :gallery
  get 'index/index'
  resource :calendar, only: [:index], controller: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  layout 'page'
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  layout 'page'
  def index
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  layout 'page'
  def index
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	
	def index
		@array = []
		for i in 0..6
			@array.push([0]*7)
		end
		@month = Date.today.strftime("%B")
		@year = Date.today.strftime("%Y")
		first_day = Date.today.at_beginning_of_month.strftime("%A")
		last_day = Date.today.end_of_month.strftime("%e").to_i
		day = 0
		case first_day
		when "Sunday"
			day = 0
		when "Monday"
			day = 1
		when "Tuesday"
			day = 2
		when "Wednesday"
			day = 3
		when "Thursday"
			day = 4
		when "Friday"
			day = 5
		when "Saturday"
			day = 6
		end

		week = 0
		diaActual = 1
		cont = 0
		
		for i in (0..@array.size-1)
			for j in (0..@array[i].size-1)
				if i == 0 and j < 5
					@array[i][j] = 0
				else				
					@array[i][j] = diaActual
					print "#{@array[i][j]}\s"
					diaActual +=1
				end
			end
			print "\n"
			if diaActual >= last_day then
				print "#{'entro'}"
				break
			end
		end
		cont = 0
		for i in(0..@array[4].size - 1)
			if @array[4][i] > last_day then
				@array[4][i] = (Date.today.at_beginning_of_month + (cont)).strftime("%e")
				cont +=1
			end
		end

		k = @array[0].size - 1
		cont = 0
		while k >= 0
			if @array[0][k] == 0 then
				@array[0][k] = (Date.today.prev_month.end_of_month - cont).strftime("%e")
				cont += 1
			end
			k -= 1
		end

	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/gallery/index.html.erb
<h1>Gallery#index</h1>
<p>Find me in app/views/gallery/index.html.erb</p>

app/views/index/index.html.erb
<div class="container">
  <h2 id="titulo-calendario">¿PARA CUANDO DESEAS TUS FLORES?</h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-auto">
      <input type="button" id="botonAtras" name="Atras" value="Atras" style="display:inline-block;width:80px;height:25px;z-index:0;">
    </div>
    <div class="col-lg-9">
      <div id="wb_textTeader">
        <span style="color:#606060;font-family:Arial;font-size:21px;"><%= @month + " - " + (@year.to_s) %></span>
      </div>
    </div>
    <div class="col-md-auto">
      <input type="button" id="BotonSiguiente" name="Siguiente" value="Siguiente" style="display:inline-block;width:80px;height:25px;z-index:2;">
    </div>
  </div>
  <% days = ["Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"] %>
  <div id="container">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <% days.each do |day| %>
          <th>
            <%= day %>
          </th>
          <% end %>
        </tr>
      </thead>
      <tbody>

        <% for i in 0..4%>
          <tr>
            <% for j in 0..6%>
              <td>
                <button type="button" class="btn btn-light" style="padding: 5px; width: 60px; height: 60px"><%= @array[i][j] %></button>
              </td>
            <%end%>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>


</div>

app/views/layouts/_menu.html.erb
<nav class="navegacion-principal clearfix">
  <%= link_to root_path do %>
    <%= "Inicio" %>
  <% end %>
  <%= link_to gallery_path do %>
    <%= "Galeria" %>
  <% end %>
  <%= link_to about_path do %>
    <%= "Nosotros" %>
  <% end %>
  <%= link_to contact_path do %>
    <%= "Contacto" %>
  <% end %>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'normalize', :media => "all" %>
    <%= stylesheet_link_tag 'main', :media => "all" %>
    <%= stylesheet_link_tag 'calendar', :media => "all" %>
    <%= stylesheet_link_tag 'application', 'https://use.fontawesome.com/releases/v5.7.2/css/all.css' %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Amatic+SC|Oswald|PT+Sans' %>

    <%= stylesheet_link_tag 'application', 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', 'https://unpkg.com/gijgo@1.9.11/css/gijgo.min.css' %>

    <%= stylesheet_link_tag 'application', 'http://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>

    <%= javascript_include_tag 'application', 'http://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' %>
    
    <%= javascript_include_tag 'application', 'https://unpkg.com/gijgo@1.9.11/js/gijgo.min.js' %>

    <%= javascript_include_tag 'application', "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" %>

    <%= javascript_include_tag 'application', "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>


    <%= javascript_include_tag "application" %>
    <%= yield :javascript_includes %>
  </head>

  <body>
    <header class="site-header">
      <div class="hero">
          <div class="contenido-header">
              <nav class="redes-sociales">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
              </nav>
              <div class="nombre-pagina">
                <h1>LAS FLORES DEL DIA</h1>
              </div>
            </div>
      </div><!--hero-->
    </header>

    <div class="barra">
        <div class="contenedor clearfix">
          <div class="logo">
            <%= link_to root_path do %>
              <%= image_tag("Logo-Las-Flores-del-dia-Pequeño-1.png", :alt => "logoflores") %>
            <% end %>
            
          </div>
          <div class="menu-movil">
            <span></span>
            <span></span>
            <span></span>
          </div>
          
          <%= render "layouts/menu" %>

        </div> <!--.contenedor-->
    </div><!--.barra-->
    <%= yield %>
    <footer class="site-footer">
      <div class="contenedor clearfix">
          <div class="footer-informacion">
              <p>Espectaculares flores para ti.</p>
          </div>
          <div class="menu">
              <h3>REDES <span>SOCIALES</span></h3>
              <nav class="redes-sociales">
                  <a href="#"><i class="fab fa-facebook-f"></i></a>
                  <a href="#"><i class="fab fa-instagram"></i></a>
                </nav>
          </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProyectoRails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'normalize', :media => "all" %>
  <%= stylesheet_link_tag 'main', :media => "all" %>

  <%= stylesheet_link_tag 'application', 'https://use.fontawesome.com/releases/v5.7.2/css/all.css' %>

  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Amatic+SC|Oswald|PT+Sans' %>

  <%= stylesheet_link_tag 'application', 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css' %>

  <%= javascript_include_tag 'application', 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="barra">
    <div class="contenedor clearfix">
      <div class="logo">
        <%= link_to root_path do %>
          <%= image_tag("Logo-Las-Flores-del-dia-Pequeño-1.png", :alt => "logoflores") %>
        <% end %>
      </div>
      <div class="menu-movil">
        <span>
        </span>
        <span>
        </span>
        <span>
        </span>
      </div>
      
      <%= render "layouts/menu"%>

    </div>
    <!--.contenedor-->
  </div>
  <!--.barra-->

  <%= yield %>

  <footer class="site-footer">
    <div class="contenedor clearfix">
      <div class="footer-informacion">
        <p>
          Espectaculares flores para ti.
        </p>
      </div>
      <div class="menu">
        <h3>
          REDES
          <span>
            SOCIALES
          </span>
        </h3>
        <nav class="redes-sociales">
          <a href="#">
            <i class="fab fa-facebook-f">
            </i>
          </a>
          <a href="#">
            <i class="fab fa-instagram">
            </i>
          </a>
        </nav>
      </div>
    </div>
  </footer>
</body>
</html>